spin_manifest_version = "1"


version = "0.1.0"
##authors = ["Constanze <einentlein@gmail.com>"]
description = "Tiny Fermyon Cloud application"
##ORIGINALauthors = ["Ryan Levick <me@ryanlevick.com>"]
##description = "A small application written in spin"
name = "todo"
trigger = { type = "http", base = "/" }


[[component]]
id = "blog-api"
source = "target/wasm32-wasi/release/blog.wasm"
allowed_http_hosts = []
sqlite_databases = ["default"]
[component.trigger]
route = "/api/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*", "Cargo.toml"]

[[component]]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.2/spin_static_fs.wasm", digest = "sha256:65456bf4e84cf81b62075e761b2b0afaffaef2d0aeda521b245150f76b96421b" }
id = "fileserver"
files = [{ source = "static", destination = "/" }]
[component.trigger]
route = "/..."